// Game constants for Shadow Duel Arena

export const CHARACTERS = {
  mage: {
    id: 'mage' as const,
    name: 'Mage',
    emoji: '🧙‍♂️',
    baseHP: 80,
    baseEnergy: 60,
    unlocked: true,
    description: 'High damage, low HP. Master of elemental magic.',
  },
  knight: {
    id: 'knight' as const,
    name: 'Knight',
    emoji: '⚔️',
    baseHP: 100,
    baseEnergy: 50,
    unlocked: true,
    description: 'Balanced warrior with sword and shield.',
  },
  ranger: {
    id: 'ranger' as const,
    name: 'Ranger',
    emoji: '🏹',
    baseHP: 90,
    baseEnergy: 55,
    unlocked: true,
    description: 'Fast and agile archer with keen aim.',
  },
  assassin: {
    id: 'assassin' as const,
    name: 'Assassin',
    emoji: '🗡️',
    baseHP: 70,
    baseEnergy: 65,
    unlocked: false,
    unlockLevel: 5,
    description: 'Glass cannon with deadly precision.',
  },
  tank: {
    id: 'tank' as const,
    name: 'Tank',
    emoji: '🛡️',
    baseHP: 130,
    baseEnergy: 45,
    unlocked: false,
    unlockLevel: 10,
    description: 'High HP, low damage. Unstoppable defender.',
  },
  healer: {
    id: 'healer' as const,
    name: 'Healer',
    emoji: '✨',
    baseHP: 95,
    baseEnergy: 60,
    unlocked: false,
    unlockLevel: 15,
    description: 'Support specialist with healing powers.',
  },
};

export const ABILITIES = {
  basic_attack: {
    id: 'basic_attack' as const,
    name: 'Attack',
    description: 'Strike your enemy',
    damage: 20,
    energyCost: 10,
    cooldown: 0,
    category: 'attack' as const,
    unlocked: true,
  },
  rest: {
    id: 'rest' as const,
    name: 'Rest',
    description: 'Recover 15 energy and lose 5 HP',
    damage: 0,
    energyCost: 0,
    cooldown: 0,
    category: 'support' as const,
    unlocked: true,
  },
  defend: {
    id: 'defend' as const,
    name: 'Defend',
    description: 'Block 50% damage next turn',
    damage: 0,
    energyCost: 15,
    cooldown: 0,
    category: 'defense' as const,
    unlocked: true,
  },
  fireball: {
    id: 'fireball' as const,
    name: 'Fireball',
    description: 'Deal 35 fire damage',
    damage: 35,
    energyCost: 20,
    cooldown: 0,
    category: 'attack' as const,
    unlocked: true,
  },
  heal: {
    id: 'heal' as const,
    name: 'Heal',
    description: 'Restore 30 HP',
    damage: 0,
    energyCost: 25,
    cooldown: 0,
    category: 'support' as const,
    unlocked: true,
  },
  power_strike: {
    id: 'power_strike' as const,
    name: 'Power Strike',
    description: 'Deal 50 damage (2-turn cooldown)',
    damage: 50,
    energyCost: 30,
    cooldown: 2,
    category: 'attack' as const,
    unlocked: false,
  },
  energy_drain: {
    id: 'energy_drain' as const,
    name: 'Energy Drain',
    description: 'Steal 20 energy from opponent',
    damage: 0,
    energyCost: 15,
    cooldown: 0,
    category: 'support' as const,
    unlocked: false,
  },
  shield_break: {
    id: 'shield_break' as const,
    name: 'Shield Break',
    description: '25 dmg, ignores defend',
    damage: 25,
    energyCost: 20,
    cooldown: 0,
    category: 'attack' as const,
    unlocked: false,
  },
  berserk: {
    id: 'berserk' as const,
    name: 'Berserk',
    description: 'Double damage next turn but take 20 dmg',
    damage: 0,
    energyCost: 15,
    cooldown: 3,
    category: 'attack' as const,
    unlocked: false,
  },
  poison: {
    id: 'poison' as const,
    name: 'Poison',
    description: '10 dmg per turn for 3 turns',
    damage: 10,
    energyCost: 20,
    cooldown: 0,
    category: 'attack' as const,
    unlocked: false,
  },
  counter: {
    id: 'counter' as const,
    name: 'Counter',
    description: 'Reflect 30% damage if attacked',
    damage: 0,
    energyCost: 20,
    cooldown: 2,
    category: 'defense' as const,
    unlocked: false,
  },
  ultimate: {
    id: 'ultimate' as const,
    name: 'Ultimate',
    description: 'Deal 80 damage (once per battle)',
    damage: 80,
    energyCost: 50,
    cooldown: 999,
    category: 'attack' as const,
    unlocked: false,
  },
  sacrifice: {
    id: 'sacrifice' as const,
    name: 'Sacrifice',
    description: 'Lose 40 HP, gain full energy',
    damage: 0,
    energyCost: 0,
    cooldown: 999,
    category: 'support' as const,
    unlocked: false,
  },
};

export const GAME_CONFIG = {
  TURN_TIME_LIMIT: 10, // seconds per player action
  BATTLE_MAX_TURNS: 10,
  ENERGY_REGEN_PER_TURN: 0,
  TIMEOUT_HP_PENALTY: 5,
  
  XP_PER_WIN: 50,
  XP_PER_LOSS: 20,
  XP_PER_LEVEL: 100,
  
  COINS_PER_WIN: 100,
  COINS_PER_LOSS: 50,
  
  RANK_POINTS_WIN: 25,
  RANK_POINTS_LOSS: -15,
  
  RAID_BOSS_TRIGGER: 10, // min players
  RAID_BOSS_DURATION: 600, // 10 minutes
  RAID_BOSS_HP: 5000,
  
  SHADOW_RETENTION_DAYS: 7,
  MAX_ONLINE_DISPLAY: 9999,
  
  RANK_TIERS: {
    BRONZE: [0, 100],
    SILVER: [100, 300],
    GOLD: [300, 600],
    PLATINUM: [600, 1000],
    DIAMOND: [1000, 2000],
    LEGEND: [2000, Infinity],
  },
};

export const ACHIEVEMENTS = {
  first_blood: {
    id: 'first_blood',
    name: 'First Blood',
    description: 'Win your first battle',
    emoji: '⭐',
    points: 10,
  },
  hot_streak: {
    id: 'hot_streak',
    name: 'Hot Streak',
    description: 'Win 5 battles in a row',
    emoji: '🔥',
    points: 25,
  },
  perfectionist: {
    id: 'perfectionist',
    name: 'Perfectionist',
    description: 'Win without taking damage',
    emoji: '💯',
    points: 50,
  },
  shadow_hunter: {
    id: 'shadow_hunter',
    name: 'Shadow Hunter',
    description: 'Defeat 100 shadows',
    emoji: '👻',
    points: 100,
  },
  dragon_slayer: {
    id: 'dragon_slayer',
    name: 'Dragon Slayer',
    description: 'Complete 10 raids',
    emoji: '🐉',
    points: 150,
  },
  legendary: {
    id: 'legendary',
    name: 'Legendary',
    description: 'Reach Legend rank',
    emoji: '🏆',
    points: 200,
  },
  energy_master: {
    id: 'energy_master',
    name: 'Energy Master',
    description: 'Win with 0 energy remaining',
    emoji: '⚡',
    points: 30,
  },
  survivor: {
    id: 'survivor',
    name: 'Survivor',
    description: 'Win with less than 10 HP',
    emoji: '🩸',
    points: 40,
  },
};
